schema: "classroom50/repo-config/v1"
classroom: "etc5523"
assignment: "assignment-3"
owner:
  username: "nwat0027"
  id: 266900961
  accepted_at: "2026-10-07T02:07:09Z"
source:
  owner: "ETC5523-2026"
  owner_id: 265932295
  repo: "assignment-3"
  branch: "main"
